server:
  port: 8082

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/oms?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 19960321ASd
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      springframework: INFO
    com:
      example: INFO